name: 'Release SDK in multiple technologies fully automtically'
description: 'Greet someone and record the time'
author: DX Heroes (https://www.dxheroes.io)
branding:
  icon: zap
  color: green  

inputs:
  package-name:
    description: 'Name of the package to release'
    required: true
  release-type:
    description: 'Type of package to release'
    required: true
    default: test # Possible values: [test, node]
  with-release-please:
    description: 'Arbitrary parameters to pass to release-please. See https://github.com/google-github-actions/release-please-action/#configuration for more information.'
    required: false

.set-inputs: &set-inputs
  ${{ inputs.with-release-please }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - run: echo "Hello ${{ inputs.package-name }}! ${{ inputs.release-type }}."
      shell: bash
    # Validate the action parameters
    - name: GH Action Validation
      run: 'node dist/index.js --package-name ${{ inputs.package-name }} --release-type ${{ inputs.release-type }}'
      shell: bash

    # Processing the package release with release-please
    - name: release-please
      uses: google-github-actions/release-please-action@v3
      with:
        <<: *set-inputs
        release-type: ${{ inputs.release-type }}
        package-name: ${{ inputs.package-name }}

    # Publishing the package to npmjs.com if the release is a node package
    - name: Publish to npmjs.com
      if: contains(github.event.head_commit.message, 'chore(release)') && inputs.release-type == 'node'
      uses: ./actions/publish-npm.yml
