name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  type:
    description: 'Type of package to release'
    required: true
    default: test # Possible values: [test, node]

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  # using: 'node16'
  # main: 'dist/index.js'
  using: 'composite'
  steps:
    - name: Checks
      run: 'node dist/index.js'
      shell: bash
    - name: release-plase
      uses: google-github-actions/release-please-action@v3.7.10
      with:
        release-type: node
        package-name: hello-world
    - name: Publish test
      if: inputs.type == 'test'
      run: 'echo "Publishing test successfull"'
      shell: bash
    - name: Publish to npmjs.com
      if: contains(github.event.head_commit.message, 'chore(release)') && inputs.type == 'node'
      uses: ./actions/publish-npm.yml
