# This workflow will publish a package to npmjs.com when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to npmjs.com
description: This workflow will publish a package to npmjs.com when a release is created
 
inputs:
  package-path:
    description: 'The path to the package directory'
    required: false
    default: '.'
  node-version:
    description: 'The version of node to use'
    required: false
    default: 'latest'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org/
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm publish --access public
      shell: bash
      working-directory: ${{ inputs.package-path }}
      env:
        NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}